org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

systemProp.https.protocols=TLSv1.2

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=goety_invasion
mod_name=Goety & Invasion
mod_license=All Rights Reserved
mod_version=1.1.2
mod_group_id=com.tenken_amainu.goety_invasion
mod_authors="TenkenAmainu , Vulmoon_XwX , Htohtosgoy , Komeiji_Jirai , JC_Minecraft87"
mod_description=.