modLoader="javafml"
loaderVersion="[47,)"
license="Goety & Invasion Custom License"
[[mods]]
modId="goety_invasion"
version="1.1.2"
displayName="Goety & Invasion"
authors="TenkenAmainu , Vulmoon_XwX , Htohtosgoy , Komeiji_Jirai , JC_Minecraft87"
logoFile="goety_invasion.png"
credits=""
[[dependencies.goety_invasion]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="${forge_version_range}" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.goety_invasion]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.goety_invasion]]
modId="curios"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
ordering="AFTER"
side="BOTH"
versionRange="[0,)"
[[dependencies.goety_invasion]]
modId="goety"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
ordering="AFTER"
side="BOTH"
versionRange="[0,)"
[[dependencies.goety_invasion]]
modId="illagerinvasion"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
ordering="AFTER"
side="BOTH"
versionRange="[0,)"
[[dependencies.goety_invasion]]
modId="puzzleslib"
mandatory=false
# This version range declares a minimum of the current minecraft version up to but not including the next major version
ordering="AFTER"
side="BOTH"
versionRange="[0,)"
# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
